feat: task done
lbrezgin/rack-app pull request #1
Opened 2024-04-22 19:44 UTC by lbrezgin

2024-04-23 07:19 UTC, BubuntuClu commented on app.rb
> +class App
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2024-04-23 07:19 UTC, BubuntuClu commented on app.rb
> +        [
сделай метод с генераций ответа

2024-04-23 07:19 UTC, BubuntuClu commented on app.rb
> +    if req.path_info == "/time" && format
разбей на методы дерево ифов, чтобы понятней было "какую историю ты рассказываешь через код"

2024-04-23 07:19 UTC, BubuntuClu commented on app.rb
> +    format.reject { |form| form if @formats.keys.include?(form) }
ты дважды проходишь по параметрам, сначала чтобы понять есть ли ошибки, а потом при генерации строки времени. за один раз надо бы получить все нужные тебе данные

2024-04-23 16:08 UTC, BubuntuClu commented on app.rb
> +  def give_time(time_formatter)
а зачем отдельный метод на каждое сообщение? сделай один с параметрами кода ответа и текста

2024-04-23 16:08 UTC, BubuntuClu commented on app.rb
> +      if time_formatter.time_format[0].empty?
ты тут вызвал логику класса TimeFormatter и потом в каждой из веток еще раз вызываешь этот же код. это очень плохо, нужно каким-то образом кэшировать результат выполнения кода

разбей код в TimeFormatter на действия- new/call/success?/time_string/error_string
так ты сможешь из это класса арр вызывать нужное действие

2024-04-23 21:54 UTC, lbrezgin commented on app.rb
> +      "hour" => "%k",
да, но я нашел изначально что часовой формат это %k. хз

2024-04-24 09:35 UTC, BubuntuClu requested changes

2024-04-24 09:35 UTC, BubuntuClu commented on time_formatter.rb
> +    format_time
нельзя в инициализацию помещать вызов логики

2024-04-24 09:35 UTC, BubuntuClu commented on time_formatter.rb
> +    @time_string = Time.now.strftime(string[0..-2])
а надо вычисления делать если есть ошибки? ты тратишь ресурс сервера на лищние операции

2024-04-25 06:48 UTC, BubuntuClu commented on time_formatter.rb
> +    @time_string = Time.now.strftime(string[0..-2]) if error_string.empty?
ну, имелось в виду конечно что ты сделаешь отделные методы на получение ошибки и времени. ну, пусть будет так

2024-04-25 21:35 UTC, merged